# Generated by Django 5.1.3 on 2024-11-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_referal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referal_code',
            new_name='reference_code',
        ),
    ]
